
default: &default
  adapter: postgis
  schema_search_path: public,postgis
  postgis_extension: postgis
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
