# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef528ebe9ff96334319ba2606586462b1146af351da31cf72242b23ff12379da3cd21e227fe2ce632262f36365ec60462407274f565e1a72389a334d0da9e44e

test:
  secret_key_base: be7ba97f5f7e36bf599f5d9312bd8793f470c83d2989f6f5cdfeb8cb6e42433ed5358d0f6ad48a1d3f6d63dfc0e6ce164cbc52ca62d82c9bbe2856de7849051b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
